# Generated by Django 4.1.4 on 2022-12-11 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Модель камеры')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to="media/<class 'django.contrib.auth.models.User'>", verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('gps', models.CharField(max_length=50, verbose_name='Координаты')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photon.camera', verbose_name='Камера')),
                ('category', models.ManyToManyField(blank=True, to='photon.category', verbose_name='Категория')),
                ('person', models.ManyToManyField(blank=True, to='photon.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотки',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomad')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватар')),
                ('fio', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Мой путь')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('gender', models.CharField(choices=[['male', 'Мужской'], ['female', 'Женский']], default='male', max_length=10, null=True, verbose_name='Пол')),
                ('facebook', models.CharField(blank=True, max_length=20, null=True, verbose_name='На созвоне')),
                ('gear', models.ManyToManyField(blank=True, to='photon.camera', verbose_name='Камера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photon.snapshot', verbose_name='Пост')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
