# Generated by Django 4.1.4 on 2022-12-17 09:52

from django.db import migrations, models
import photon.models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=photon.models.user_directory_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='photo',
            field=models.FileField(upload_to="<class 'django.contrib.auth.models.User'>/%Y/%m/%d", verbose_name='Фото'),
        ),
    ]
