# Generated by Django 4.1.4 on 2022-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0005_remove_profile_facebook_profile_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cameras',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Камеры'),
        ),
    ]
