# Generated by Django 4.1.4 on 2022-12-17 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photon.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photon', '0006_profile_cameras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='photon.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='photo',
            field=models.FileField(upload_to=photon.models.user_directory_path1, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Регион'),
        ),
    ]
