# Generated by Django 4.1.4 on 2022-12-17 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photon', '0007_alter_snapshot_author_alter_snapshot_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
