# Generated by Django 4.1.4 on 2022-12-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0009_alter_sublist_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='person',
            field=models.ManyToManyField(blank=True, to='photon.person', verbose_name='Человек'),
        ),
    ]
