# Generated by Django 4.1.4 on 2022-12-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0010_alter_snapshot_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_in_snap',
            field=models.IntegerField(default=1),
        ),
    ]
