# Generated by Django 4.1.4 on 2022-12-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0011_person_person_in_snap'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='snap_count',
            field=models.IntegerField(default=0, verbose_name='Всего фотографий'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_in_snap',
            field=models.IntegerField(default=1, verbose_name='Присутствие на фото'),
        ),
    ]
