# Generated by Django 4.1.4 on 2022-12-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photon', '0012_category_snap_count_alter_person_person_in_snap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='category',
            field=models.ManyToManyField(blank=True, to='photon.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='photo',
            field=models.FileField(upload_to='<function user_directory_path1 at 0x000001C07DADB0A0>%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
